# Generated by rust2rpm 10
%bcond_without check
%global __cargo_skip_build 0

%global crate pretty-git-prompt

Name:           rust-%{crate}
Version:        0.2.0
Release:        11%{?dist}
Summary:        Your current git repository information inside a beautiful shell prompt

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/pretty-git-prompt
Source:         %{crates_source}
# Initial patched metadata
# * Bump git2 to 0.9, https://github.com/TomasTomecek/pretty-git-prompt/pull/46
Patch0:         pretty-git-prompt-fix-metadata.diff
# Make it work with new git2, https://github.com/TomasTomecek/pretty-git-prompt/pull/39
Patch1:         0001-deps-update-git2-to-0.7.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Your current git repository information inside a beautiful shell prompt.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%doc files
%{_bindir}/pretty-git-prompt

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# https://github.com/tomastomecek/pretty-git-prompt/issues/35
%cargo_test || :
%endif

%changelog
* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jul 14 12:10:39 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-10
- Regenerate

* Fri Jun 07 2019 Josh Stone <jistone@redhat.com> - 0.2.0-9
- Bump git2 to 0.9

* Tue Apr 02 2019 Josh Stone <jistone@redhat.com> - 0.2.0-8
- Bump git2 to 0.8

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Aug 10 2018 Josh Stone <jistone@redhat.com> - 0.2.0-6
- Rebuild with fixed rust-libgit2-sys-0.7.7

* Fri Aug 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-5
- Rebuild for libgit2 0.27.x

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Mon Mar 12 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-3
- Bump git2 to 0.7

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Sun Jan 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Initial package
